development:
  adapter: postgresql
  encoding: unicode
  database: xxx
  pool: 5
  username: xxx
  password: xxx
  host: localhost
test:
  adapter: postgresql
  encoding: unicode
  database: xxx
  pool: 5
  username: xxx
  password: xxx
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: xxxx
  pool: 5
  username: xxx
  password: xxxx
  host: localhost
