# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f545d37f647f6640431759ef87ea00602c15461eebacc07a162b6b196a4ff5da1737c0901132b19807a95942e48548194cf87fb930e86e3f8cf6f1ebe114e37f

test:
  secret_key_base: d257db4543d8778dce32b1fd732df8d21153448c09aafa21deb9c438e605793cbb43d355393fc61e5cf69cf1d0d78bb23adde448aed3338e7678b7a22c82895f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
